export NVM_DIR="/Users/connormckelvey/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

[ -s "/Users/connormckelvey/.jabba/jabba.sh" ] && source "/Users/connormckelvey/.jabba/jabba.sh"
